name: climate12k
dependencies:
    - python=3.7
    - pandas
    - pyqt  # necessary for lipd...
    - pip
    - pytest
    - pytest-sugar
    - pytest-html
    - jupyter
    - notebook
    - xlsxwriter
    - xlrd
    - openpyxl
    - geopandas
    - pip:
        - lipd
        - latlon-utils
