name: climate12k
dependencies:
    - pandas
    - pyqt  # necessary for lipd...
    - pip
    - pytest
    - pytest-sugar
    - pytest-html
    - jupyter
    - xlsxwriter
    - xlrd
    - pip:
        - lipd
